"""Add missing columns to invoice_items

Revision ID: 56314537ad87
Revises: 
Create Date: 2026-01-24 16:14:02.662340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56314537ad87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hs_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('uom', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('sales_tax_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_column('discount')
        batch_op.drop_column('sales_tax_rate')
        batch_op.drop_column('uom')
        batch_op.drop_column('hs_code')

    # ### end Alembic commands ###
