"""Add lose_qty to challan_items and simplify quotation_items

Revision ID: f9d39d54015b
Revises: 56314537ad87
Create Date: 2026-01-24 16:14:35.128800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d39d54015b'
down_revision = '56314537ad87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challan_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lose_qty', sa.Integer(), nullable=True))

    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quantity')
        batch_op.drop_column('ply')
        batch_op.drop_column('pcs')
        batch_op.drop_column('flute1_roll_id')
        batch_op.drop_column('bottom_paper_id')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('flute2_roll_id')
        batch_op.drop_column('width')
        batch_op.drop_column('middle_paper_id')
        batch_op.drop_column('labour_cost')
        batch_op.drop_column('printing')
        batch_op.drop_column('flute3_roll_id')
        batch_op.drop_column('created_at')
        batch_op.drop_column('top_paper_id')
        batch_op.drop_column('printing_cost')
        batch_op.drop_column('length')
        batch_op.drop_column('printing_sides')
        batch_op.drop_column('joint_type')
        batch_op.drop_column('cartage_cost')
        batch_op.drop_column('height')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('cartage_cost', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('joint_type', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('printing_sides', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('length', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('printing_cost', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('top_paper_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('flute3_roll_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('printing', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('labour_cost', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('middle_paper_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('width', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('flute2_roll_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('bottom_paper_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('flute1_roll_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('pcs', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('ply', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'paper_grades', ['middle_paper_id'], ['id'])
        batch_op.create_foreign_key(None, 'roll_grades', ['flute3_roll_id'], ['id'])
        batch_op.create_foreign_key(None, 'roll_grades', ['flute2_roll_id'], ['id'])
        batch_op.create_foreign_key(None, 'roll_grades', ['flute1_roll_id'], ['id'])
        batch_op.create_foreign_key(None, 'paper_grades', ['top_paper_id'], ['id'])
        batch_op.create_foreign_key(None, 'paper_grades', ['bottom_paper_id'], ['id'])
        batch_op.drop_column('serial_number')

    with op.batch_alter_table('challan_items', schema=None) as batch_op:
        batch_op.drop_column('lose_qty')

    # ### end Alembic commands ###
